import { useState, useCallback } from "react";
import { trackEvent } from "@/hooks/usePageTracking";
import { ChevronDown, HelpCircle } from "lucide-react";

interface FAQItem {
  question: string;
  answer: React.ReactNode;
}

const faqData: FAQItem[] = [
  {
    question: "What does BuildSignal monitor?",
    answer: <p>BuildSignal monitors public construction permit filings, infrastructure project approvals, and related development activity in supported counties. This includes residential, commercial, and public works projects that are filed with local government offices.</p>,
  },
  {
    question: "Where does BuildSignal get its information?",
    answer: <p>BuildSignal aggregates data from public records, county permit offices, and other open government data sources. We maintain provenance tracking so you can understand where each signal originated. We do not access private or proprietary databases without authorization.</p>,
  },
  {
    question: "How frequently is information updated?",
    answer: <p>Update frequency varies by data source and county. Many supported markets are checked on a daily or weekly basis, though some sources update less frequently depending on the county's publication schedule. The dashboard shows freshness indicators where available.</p>,
  },
  {
    question: "Which markets are covered?",
    answer: <p>BuildSignal covers a growing set of counties across the United States. Coverage is not nationwide. You can search for specific counties and markets within your BuildSignal dashboard, or contact us to inquire about a specific location.</p>,
  },
  {
    question: "What is a growth signal?",
    answer: <p>A growth signal is an indication of increased or unusual construction and development activity in a specific market. Signals are generated by analyzing patterns in permit filings, project approvals, and infrastructure activity over time. A signal does not guarantee future growth — it is an indicator that warrants further investigation.</p>,
  },
  {
    question: "What does the confidence score mean?",
    answer: <p>The confidence score reflects the strength of evidence supporting a signal, based on data volume, consistency, and source reliability. It is <strong>not</strong> a prediction of investment success or market performance. A high-confidence signal means the underlying data pattern is strong; it does not eliminate the need for your own due diligence.</p>,
  },
  {
    question: "Does BuildSignal replace real-estate due diligence?",
    answer: <p><strong>No.</strong> BuildSignal is a research tool that surfaces public development activity. It does not replace legal, financial, or physical due diligence. Always conduct your own independent analysis before making investment or business decisions. BuildSignal provides intelligence, not advice.</p>,
  },
  {
    question: "How does the 14-day trial work?",
    answer: <p>You can start a 14-day free trial without providing a credit card. During the trial, you have full access to the features included in your selected plan. If you choose not to continue, your account will simply expire at the end of the 14 days. You can upgrade to a paid plan at any time during or after the trial.</p>,
  },
];

export function HomeFAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const handleToggle = useCallback((index: number) => {
    const newIndex = openIndex === index ? null : index;
    setOpenIndex(newIndex);
    if (newIndex !== null) trackEvent("homepage_faq_opened", { question: faqData[index].question });
  }, [openIndex]);

  return (
    <section id="faq" className="py-20 md:py-28 bg-surface" aria-labelledby="faq-heading">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/10 text-emerald-400 text-sm font-medium mb-4">
            <HelpCircle className="w-4 h-4" /><span>Common Questions</span>
          </div>
          <h2 id="faq-heading" className="text-3xl md:text-4xl font-bold text-ink mb-4">Frequently Asked Questions</h2>
          <p className="text-lg text-muted">Straight answers about how BuildSignal works.</p>
        </div>
        <div className="bg-canvas border border-border rounded-2xl p-2 md:p-4">
          {faqData.map((item, index) => (
            <div key={index} className="border-b border-border last:border-b-0">
              <h3>
                <button type="button" onClick={() => handleToggle(index)} aria-expanded={openIndex === index} aria-controls={`faq-content-${index}`} id={`faq-trigger-${index}`}
                  className="w-full flex items-center justify-between py-5 px-2 text-left hover:bg-surface/50 transition-colors rounded-lg focus:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500 focus-visible:ring-offset-2 focus-visible:ring-offset-canvas">
                  <span className="text-base font-medium text-ink pr-4">{item.question}</span>
                  <ChevronDown className={`w-5 h-5 text-muted flex-shrink-0 transition-transform duration-200 motion-reduce:transition-none ${openIndex === index ? "rotate-180" : ""}`} aria-hidden="true" />
                </button>
              </h3>
              <div id={`faq-content-${index}`} role="region" aria-labelledby={`faq-trigger-${index}`}
                className={`overflow-hidden transition-all duration-200 ease-in-out motion-reduce:transition-none ${openIndex === index ? "max-h-96 opacity-100" : "max-h-0 opacity-0"}`}>
                <div className="pb-5 px-2 text-muted leading-relaxed">{item.answer}</div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
